@startuml
skinparam SequenceMessageAlign center
skinparam monochrome true
skinparam shadowing false

actor Repartidor
boundary PantallaGestioEntregues <<boundary>>
control GestorEntregues <<control>>
entity Comanda <<entity>>
boundary ServeiMapaExtern <<boundary>>
boundary ServeiNotificacioExtern <<boundary>>
boundary ServeiUbicacioExtern <<boundary>>

autonumber

== Pestanya de Comandes: Accedir y pre-visualitzar detalls de comandes) ==
Repartidor -> PantallaGestioEntregues : accedirComandesPendents()
activate PantallaGestioEntregues
PantallaGestioEntregues -> GestorEntregues : consultarComandesPendentsDetall()
activate GestorEntregues

GestorEntregues -> Comanda : getComandesPendentsDetall()
activate Comanda
Comanda --> GestorEntregues : listDetailedComandas
deactivate Comanda

GestorEntregues --> PantallaGestioEntregues : listDetailedComandas
deactivate GestorEntregues
PantallaGestioEntregues -> PantallaGestioEntregues : mostrarLlistatDetallat()
note right: Mostra totes les comandes amb tota la info, distància, adreces, noms, preus.
deactivate PantallaGestioEntregues

autonumber 6
== Pestanya de Comandes: Acceptar comanda ==
Repartidor -> PantallaGestioEntregues : acceptarComanda(id)
activate PantallaGestioEntregues
PantallaGestioEntregues -> GestorEntregues : assignarRepartidorComanda(idComanda, idRepartidor)
activate GestorEntregues

GestorEntregues -> Comanda : setRepartidor(idRepartidor)
activate Comanda
Comanda --> GestorEntregues : exit
deactivate Comanda

GestorEntregues -> Comanda : actualitzarEstat("Aceptada")
activate Comanda
Comanda --> GestorEntregues : exit
deactivate Comanda

GestorEntregues --> PantallaGestioEntregues : exit (Confirmació tècnica)
deactivate GestorEntregues

PantallaGestioEntregues -> PantallaGestioEntregues : mostrarConfirmacioAceptacio()
note right: Comanda passa visualment a la pestanya 'Actives' i mostra missatge "Comanda acceptada"
deactivate PantallaGestioEntregues

autonumber 16
== Pestanya d'Actives: Iniciar enviament ==
Repartidor -> PantallaGestioEntregues : iniciarEnviament(id)
activate PantallaGestioEntregues
PantallaGestioEntregues -> GestorEntregues : coordinarIniciEnviament(idComanda)
activate GestorEntregues

GestorEntregues -> Comanda : actualitzarEstat("En camí")
activate Comanda
Comanda --> GestorEntregues : exit
deactivate Comanda

GestorEntregues -> ServeiUbicacioExtern : activarStreamPosicioGPS(idComanda, idRepartidor, idClient)
activate ServeiUbicacioExtern
ServeiUbicacioExtern --> GestorEntregues : exit
deactivate ServeiUbicacioExtern
note right of GestorEntregues: Envia posició al client.

GestorEntregues --> PantallaGestioEntregues : exit (Confirmació tècnica)
deactivate GestorEntregues

PantallaGestioEntregues -> PantallaGestioEntregues : mostrarPestanyaActivesDetall()
note right: Mostra missatge "Enviament Iniciat"
deactivate PantallaGestioEntregues

== Pestanya d'Actives: Marcar com a lliurat ==
autonumber 29
Repartidor -> PantallaGestioEntregues : comandaEntregada()
activate PantallaGestioEntregues
PantallaGestioEntregues -> GestorEntregues : finalitzarEntrega(idComanda)
activate GestorEntregues

GestorEntregues -> Comanda : actualitzarEstat("Lliurat")
activate Comanda
Comanda --> GestorEntregues : exit
deactivate Comanda

GestorEntregues -> ServeiNotificacioExtern : notificarEntregaLliurada(idComanda)
activate ServeiNotificacioExtern
ServeiNotificacioExtern --> GestorEntregues : exit
deactivate ServeiNotificacioExtern
note right of GestorEntregues: Avisa al client associat a la comanda.

GestorEntregues --> PantallaGestioEntregues : exit
deactivate GestorEntregues

PantallaGestioEntregues -> PantallaGestioEntregues : mostrarPantallaExit()
note right: mostra missatge "Comanda lliurada correctament!"
deactivate PantallaGestioEntregues

@enduml